services:
  hutao-bot:
    build: .
    container_name: hutao_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
      - ./sounds:/app/sounds